### ISSUE TITLE
Bug ao ordernar por progresso

### ISSUE THREAD

**Issue by dannRocha** [dannRocha/manga-progress#10]
Alguns mangas estão sendo organizados pelo progresso errado
Verificar a causar:
* *Verificar se os capitulos estão como string em vez de number.*
* *Verificar se o methodo pra organizar está sendo chamado.*
* *Verificar outras possiveis casos*
<h3>No top da lista</h3>

![Screenshot from 2020-09-16 23-12-27](https://user-images.githubusercontent.com/38236602/93411824-5c7ede80-f872-11ea-9be7-5499bc0cbe6b.png)
<h3>No meio da lista</h3>

![Screenshot from 2020-09-16 23-12-53](https://user-images.githubusercontent.com/38236602/93411827-5f79cf00-f872-11ea-99c4-222e1a5fd644.png)

**Comment by danroxha** [comment]
Corrigido
