### ISSUE TITLE
Fix: Atualização da capa, modo grid

### ISSUE THREAD

**Issue by dannRocha** [dannRocha/manga-progress#3]
A  fonte da imagem não é fixa, então tem que verificar o estado de cada componente da estrutura de dados e checar se há alteração

**Comment by danroxha** [comment]
Resolver o problema armazenando a imagem que teve sucesso em carregar com base64 e quardar localmente #1

**Comment by danroxha** [comment]
> Resolver o problema armazenando a imagem que teve sucesso em carregar com base64 e quardar localmente #1

Inda não implementado o armazenamendo offline das capas, mas foi corrigo a exibição da capa com a imagem com link quebrado
