### ISSUE TITLE
Lidar melhor com a obtenção de dados dos capitulos

### ISSUE THREAD

**Issue by dannRocha** [dannRocha/manga-progress#7]
## Problema
- Capítulos com numero: 01.1, 32.1 não são processados corretamente
- Capítulos especiais também são afetados

## Solução
Atualizar a expressão regular em ***daemon.js***

**Comment by dannRocha** [comment]
# Possível correção

## URLs de Teste
- https://mangahosted.com/manga/kaifuku-jutsushi-yarinaoshi-mh40648/17.2#1
- https://mangahosted.com/manga/tower-of-god-season-3-mh16776/28#1
- https://mangahosted.com/manga/all-you-need-is-kill-mh25533/1/56#11
- https://mangahosted.com/manga/shingeki-no-kyojin-attack-on-titan-mh27168/extra-01#1

## Expressão regular para [Manga Host](https://mangahosted.com/) | Capitulo atual
***\w+\d+\/(\d+|\w+.+)#***

### [Teste online](https://regex101.com/)

**Comment by dannRocha** [comment]
Tem que mudar a maneira que eh processado o progresso, já que o capitulo "atual" pode ser uma string

**Comment by danroxha** [comment]
> # Possível correção
> ## URLs de Teste
> * https://mangahosted.com/manga/kaifuku-jutsushi-yarinaoshi-mh40648/17.2#1
> * https://mangahosted.com/manga/tower-of-god-season-3-mh16776/28#1
> * https://mangahosted.com/manga/all-you-need-is-kill-mh25533/1/56#11
> * https://mangahosted.com/manga/shingeki-no-kyojin-attack-on-titan-mh27168/extra-01#1
> 
> ## Expressão regular para [Manga Host](https://mangahosted.com/) | Capitulo atual
> _**\w+\d+\/(\d+|\w+.+)#**_
> 
> ### [Teste online](https://regex101.com/)

Resolvido alterando o final da expressão regular
de
_**\w+\d+\/(\d+|\w+.+)#**_
para
_**\w+\d+\/(\d+|\w+.+)$**_
